# Generated by Django 3.2.8 on 2021-10-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('size_name', models.CharField(max_length=30)),
            ],
        ),
    ]
