# Generated by Django 3.2.8 on 2021-10-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_pizzatopping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizzasize')),
                ('toppings', models.ManyToManyField(to='pizzas.PizzaTopping')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizzatype')),
            ],
        ),
    ]
